export type InvestmentModuleId = `M${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12}`;

export type ParameterLens = "Mức hiện tại" | "Xu hướng" | "So sánh ngành" | "Độ bền" | "Kịch bản";

export type InvestmentParameter = {
  code: string;
  moduleId: InvestmentModuleId;
  moduleTitle: string;
  concept: string;
  lens: ParameterLens;
  role: "filter" | "signal" | "veto" | "validation";
};

export const PARAMETER_LENSES: ParameterLens[] = [
  "Mức hiện tại",
  "Xu hướng",
  "So sánh ngành",
  "Độ bền",
  "Kịch bản",
];

export const INVESTMENT_MODULES: Array<{
  id: InvestmentModuleId;
  title: string;
  concepts: string[];
}> = [
  {
    "id": "M1",
    "title": "NHẬN DẠNG DOANH NGHIỆP, NGÀNH VÀ VỊ THẾ",
    "concepts": [
      "nguồn doanh thu chính",
      "cơ cấu doanh thu theo phân khúc",
      "cơ cấu lợi nhuận theo phân khúc",
      "mức tập trung khách hàng",
      "mức tập trung nhà cung cấp",
      "phạm vi địa lý",
      "đồng tiền chức năng",
      "mô hình doanh thu lặp lại",
      "mức độ điều tiết",
      "mức độ thâm dụng vốn",
      "mức độ thâm dụng lao động",
      "mức độ thâm dụng dữ liệu",
      "vòng đời doanh nghiệp",
      "vị thế thị phần",
      "lợi thế chi phí",
      "quyền lực định giá",
      "chi phí chuyển đổi khách hàng",
      "hiệu ứng mạng lưới",
      "rào cản gia nhập",
      "mức độ phụ thuộc nền tảng bên thứ ba",
      "cơ cấu EBITDA theo phân khúc",
      "cơ cấu tài sản vận hành theo phân khúc",
      "mức độ tích hợp dọc",
      "mức độ tích hợp ngang",
      "độ phức tạp mô hình kinh doanh",
      "mức phụ thuộc một sản phẩm chủ lực",
      "mức phụ thuộc một khách hàng chủ lực",
      "mức phụ thuộc một nhà cung cấp chủ lực",
      "mức phụ thuộc một kênh phân phối",
      "mức phụ thuộc một khu vực địa lý",
      "mức độ điều tiết giá",
      "mức độ điều tiết giấy phép",
      "tốc độ quay vòng vốn đầu tư",
      "khả năng thay thế lao động bằng công nghệ",
      "khả năng tạo giá trị từ dữ liệu",
      "mức độ thâm dụng sở hữu trí tuệ",
      "vị thế chi phí tương đối",
      "vị thế thương hiệu tương đối",
      "vị thế mạng lưới phân phối",
      "vị thế công nghệ tương đối",
      "quyền lực thương lượng với khách hàng",
      "quyền lực thương lượng với nhà cung cấp",
      "rào cản gia nhập ngành",
      "rủi ro sản phẩm thay thế",
      "cường độ cạnh tranh nội ngành",
      "khả năng mở rộng quy mô",
      "khả năng quốc tế hóa",
      "độ linh hoạt chuyển đổi mô hình",
      "mức độ phụ thuộc trợ cấp",
      "mức độ phụ thuộc đấu thầu công",
      "mức độ phụ thuộc đối tác chiến lược",
      "chi phí chuyển đổi khỏi nền tảng bên thứ ba",
      "độ phù hợp giữa tài sản và mô hình doanh thu",
      "độ phù hợp giữa nhân lực và chiến lược",
      "độ phù hợp giữa vốn và tốc độ tăng trưởng",
      "độ rõ ràng của lợi thế cạnh tranh",
      "thời gian duy trì lợi thế cạnh tranh",
      "tốc độ xói mòn lợi thế cạnh tranh",
      "mức độ thay đổi cấu trúc ngành",
      "độ nhạy với chuyển dịch hành vi khách hàng"
    ]
  },
  {
    "id": "M2",
    "title": "CHẤT LƯỢNG DOANH THU VÀ NHU CẦU",
    "concepts": [
      "tăng trưởng doanh thu hữu cơ",
      "tăng trưởng do M&A",
      "tăng trưởng sản lượng",
      "tăng trưởng giá bán",
      "thay đổi cơ cấu sản phẩm",
      "doanh thu lặp lại",
      "doanh thu hợp đồng dài hạn",
      "backlog chưa ghi nhận",
      "tỷ lệ gia hạn",
      "tỷ lệ rời bỏ khách hàng",
      "giá trị vòng đời khách hàng",
      "chi phí thu hút khách hàng",
      "doanh thu trên khách hàng",
      "doanh thu theo cửa hàng hiện hữu",
      "doanh thu trên đơn vị công suất",
      "tỷ lệ hoàn trả/hủy đơn",
      "doanh thu bên liên quan",
      "doanh thu chưa thực hiện",
      "doanh thu theo mùa vụ",
      "độ nhạy doanh thu với chu kỳ",
      "giá bán bình quân",
      "sản lượng tiêu thụ",
      "cơ cấu sản phẩm",
      "cơ cấu khách hàng",
      "cơ cấu kênh bán",
      "tỷ lệ doanh thu lặp lại",
      "tỷ lệ doanh thu theo hợp đồng dài hạn",
      "tỷ lệ doanh thu đặt trước",
      "giá trị đơn hàng tồn đọng",
      "tốc độ chuyển backlog thành doanh thu",
      "tỷ lệ gia hạn hợp đồng",
      "tỷ lệ rời bỏ khách hàng có trọng số doanh thu",
      "tỷ lệ giữ chân doanh thu thuần",
      "doanh thu cohort theo thời gian",
      "doanh thu trên điểm bán",
      "doanh thu trên nhân viên bán hàng",
      "doanh thu biên trên công suất bổ sung",
      "tỷ lệ khách hàng mới",
      "CAC biên của khách hàng mới",
      "thời gian hoàn vốn CAC",
      "giá trị vòng đời khách hàng sau chi phí phục vụ",
      "tỷ lệ LTV/CAC",
      "độ co giãn cầu theo giá",
      "khả năng tăng giá bán",
      "độ trễ truyền giá",
      "mức độ khuyến mại",
      "tỷ lệ trả hàng",
      "tỷ lệ hủy đơn",
      "tỷ lệ sản phẩm lỗi ảnh hưởng doanh thu",
      "tỷ lệ doanh thu từ đổi mới sản phẩm",
      "tốc độ thương mại hóa sản phẩm mới",
      "thị phần doanh thu",
      "thị phần sản lượng",
      "mức thâm nhập thị trường",
      "tần suất mua lại",
      "giá trị giỏ hàng bình quân",
      "tỷ lệ chuyển đổi khách hàng",
      "lưu lượng khách hàng",
      "mức độ mùa vụ doanh thu",
      "độ lệch doanh thu so với hướng dẫn"
    ]
  },
  {
    "id": "M3",
    "title": "CHI PHÍ, BIÊN LỢI NHUẬN VÀ HIỆU QUẢ VẬN HÀNH",
    "concepts": [
      "biên lợi nhuận gộp",
      "biên EBITDA",
      "biên EBIT",
      "biên lợi nhuận ròng",
      "chi phí nguyên vật liệu",
      "chi phí năng lượng",
      "chi phí nhân sự",
      "chi phí logistics",
      "chi phí thuê",
      "chi phí nền tảng/cloud",
      "chi phí bán hàng",
      "chi phí quản lý",
      "đòn bẩy hoạt động",
      "điểm hòa vốn",
      "khả năng chuyển chi phí sang giá bán",
      "hiệu suất công suất",
      "tỷ lệ phế phẩm",
      "năng suất lao động",
      "chi phí bảo hành",
      "chi phí tuân thủ",
      "biên lợi nhuận gộp theo phân khúc",
      "biên đóng góp",
      "đòn bẩy hoạt động gia tăng",
      "biên an toàn trên điểm hòa vốn",
      "tỷ trọng chi phí cố định",
      "tỷ trọng chi phí biến đổi",
      "chi phí nguyên vật liệu trên doanh thu",
      "chi phí năng lượng trên doanh thu",
      "chi phí nhân công trên doanh thu",
      "chi phí logistics trên doanh thu",
      "chi phí thuê mặt bằng trên doanh thu",
      "chi phí bán hàng trên doanh thu",
      "chi phí quản lý trên doanh thu",
      "chi phí nghiên cứu phát triển trên doanh thu",
      "chi phí bảo hành trên doanh thu",
      "chi phí chất lượng kém",
      "năng suất lao động điều chỉnh chất lượng",
      "doanh thu trên nhân viên",
      "lợi nhuận trên nhân viên",
      "công suất thiết kế",
      "tỷ lệ sử dụng công suất",
      "hiệu suất thiết bị tổng thể",
      "tỷ lệ phế phẩm theo nguyên nhân",
      "tỷ lệ hoàn thành đúng hạn",
      "vòng đời sản xuất",
      "thời gian chu kỳ đơn hàng",
      "hiệu quả mua hàng",
      "mức tiết kiệm chi phí mua hàng",
      "khả năng thay thế nguyên liệu",
      "mức độ tự động hóa",
      "chi phí điện toán đám mây trên doanh thu",
      "chi phí phục vụ mỗi khách hàng",
      "chi phí trên mỗi giao dịch",
      "chi phí trên mỗi đơn vị sản phẩm",
      "độ nhạy biên lợi nhuận với giá đầu vào",
      "độ nhạy biên lợi nhuận với tỷ giá",
      "độ nhạy biên lợi nhuận với tiền lương",
      "tốc độ phục hồi biên lợi nhuận",
      "mức độ bền vững của tiết giảm chi phí",
      "khoảng cách biên lợi nhuận so với đối thủ"
    ]
  },
  {
    "id": "M4",
    "title": "DÒNG TIỀN, VỐN LƯU ĐỘNG VÀ CHẤT LƯỢNG LỢI NHUẬN",
    "concepts": [
      "dòng tiền hoạt động",
      "dòng tiền tự do",
      "tỷ lệ chuyển EBITDA thành tiền",
      "tỷ lệ chuyển lợi nhuận thành tiền",
      "khoản phải thu",
      "số ngày phải thu",
      "hàng tồn kho",
      "số ngày tồn kho",
      "khoản phải trả",
      "số ngày phải trả",
      "chu kỳ chuyển đổi tiền mặt",
      "capex duy trì",
      "capex tăng trưởng",
      "chi phí được vốn hóa",
      "accruals",
      "thu nhập bất thường",
      "dòng tiền sau cổ tức",
      "dòng tiền sau mua lại cổ phiếu",
      "tiền bị hạn chế sử dụng",
      "nghĩa vụ tiền mặt ngoài bảng",
      "dòng tiền hoạt động trước vốn lưu động",
      "tỷ lệ chuyển EBITDA thành tiền sau capex duy trì",
      "tỷ lệ chuyển lợi nhuận ròng thành tiền",
      "dòng tiền tự do cho doanh nghiệp",
      "dòng tiền tự do cho cổ đông",
      "tỷ lệ thiếu đầu tư capex duy trì",
      "suất sinh lời capex tăng trưởng",
      "tỷ lệ capex trên doanh thu",
      "tỷ lệ capex trên khấu hao",
      "chu kỳ tiền mặt điều chỉnh mùa vụ",
      "số ngày phải thu điều chỉnh factoring",
      "số ngày tồn kho điều chỉnh giảm giá",
      "số ngày phải trả điều chỉnh reverse factoring",
      "tỷ lệ phải thu quá hạn",
      "tỷ lệ dự phòng phải thu",
      "tỷ lệ tồn kho chậm luân chuyển",
      "tỷ lệ giảm giá tồn kho",
      "tỷ lệ người mua trả trước",
      "tỷ lệ chi phí trả trước",
      "tỷ lệ doanh thu chưa thực hiện",
      "tỷ lệ tiền mặt bị hạn chế",
      "dòng tiền từ thanh lý tài sản",
      "dòng tiền từ trợ cấp và hoàn thuế",
      "dòng tiền từ factoring",
      "mức sử dụng reverse factoring",
      "chất lượng khoản phải thu",
      "chất lượng hàng tồn kho",
      "chất lượng khoản phải trả",
      "độ biến động vốn lưu động",
      "độ nhạy vốn lưu động với tăng trưởng",
      "mức độ vốn hóa chi phí",
      "tỷ lệ chi phí không bằng tiền",
      "tỷ lệ lợi nhuận bất thường",
      "tỷ lệ thu nhập liên doanh không bằng tiền",
      "tỷ lệ cổ tức nhận bằng tiền",
      "khả năng tự tài trợ tăng trưởng",
      "mức thiếu hụt tài trợ vốn lưu động",
      "dòng tiền sau nghĩa vụ bắt buộc",
      "dòng tiền khả dụng cho phân bổ vốn",
      "độ nhất quán giữa lợi nhuận và tiền mặt"
    ]
  },
  {
    "id": "M5",
    "title": "BẢNG CÂN ĐỐI, ĐÒN BẨY VÀ KHẢ NĂNG SỐNG SÓT",
    "concepts": [
      "nợ ròng",
      "nợ/EBITDA",
      "khả năng trả lãi",
      "kỳ hạn nợ",
      "lãi suất cố định/thả nổi",
      "tài sản bảo đảm",
      "covenant tài chính",
      "tỷ lệ thanh khoản hiện hành",
      "tỷ lệ thanh khoản nhanh",
      "dự trữ tiền mặt",
      "hạn mức tín dụng chưa sử dụng",
      "mismatch kỳ hạn",
      "mismatch tiền tệ",
      "nghĩa vụ thuê",
      "nghĩa vụ hưu trí",
      "bảo lãnh và cam kết",
      "reverse factoring",
      "tập trung chủ nợ",
      "khả năng tái cấp vốn",
      "rủi ro pha loãng do huy động vốn",
      "nợ ròng trên EBITDA",
      "nợ trên vốn chủ sở hữu",
      "nợ trên tổng tài sản",
      "khả năng thanh toán lãi vay",
      "khả năng thanh toán nghĩa vụ cố định",
      "tỷ lệ thanh toán hiện hành",
      "tỷ lệ thanh toán nhanh",
      "tỷ lệ tiền mặt trên nợ ngắn hạn",
      "hồ sơ đáo hạn nợ",
      "mức tập trung đáo hạn",
      "tỷ lệ nợ lãi suất thả nổi",
      "tỷ lệ nợ lãi suất cố định",
      "chi phí nợ bình quân",
      "kỳ hạn nợ bình quân",
      "duration tài sản",
      "duration nghĩa vụ",
      "chênh lệch kỳ hạn tài sản-nợ",
      "vị thế ngoại tệ ròng",
      "chênh lệch tiền tệ tài sản-nợ",
      "tài sản thế chấp trên nợ",
      "dư địa tài sản bảo đảm",
      "dư địa covenant",
      "khoảng cách tới vi phạm covenant",
      "hạn mức tín dụng cam kết chưa sử dụng",
      "xác suất tái cấp vốn theo từng kỳ hạn",
      "phụ thuộc nguồn vốn ngắn hạn",
      "phụ thuộc một chủ nợ",
      "phụ thuộc thị trường trái phiếu",
      "nghĩa vụ thuê tài sản",
      "nghĩa vụ bảo lãnh",
      "cam kết mua hàng dài hạn",
      "nghĩa vụ ngoài bảng cân đối",
      "độ nhạy nghĩa vụ hưu trí với lãi suất",
      "thiếu hụt quỹ hưu trí",
      "nợ thuế tiềm tàng",
      "nghĩa vụ môi trường",
      "rủi ro gọi ký quỹ",
      "giá trị tài sản thanh lý",
      "khả năng sống sót 12 tháng",
      "khả năng sống sót trong stress cực đoan"
    ]
  },
  {
    "id": "M6",
    "title": "QUẢN TRỊ, PHÂN BỔ VỐN VÀ CHẤT LƯỢNG QUẢN LÝ",
    "concepts": [
      "ROIC",
      "ROE",
      "ROA",
      "incremental ROIC",
      "tỷ lệ tái đầu tư",
      "hiệu quả capex",
      "lịch sử M&A",
      "goodwill sau M&A",
      "kỷ luật cổ tức",
      "mua lại cổ phiếu",
      "phát hành thêm",
      "giao dịch bên liên quan",
      "cấu trúc quyền biểu quyết",
      "độc lập HĐQT",
      "thù lao quản lý",
      "giao dịch cổ đông nội bộ",
      "chất lượng hướng dẫn lợi nhuận",
      "độ chính xác dự báo quản lý",
      "kế nhiệm lãnh đạo",
      "văn hóa kiểm soát nội bộ",
      "ROIC hiện tại",
      "ROIC gia tăng",
      "tỷ lệ tái đầu tư hữu cơ",
      "lợi suất tái đầu tư",
      "mức tạo giá trị kinh tế",
      "chi phí vốn bình quân",
      "khoảng chênh ROIC-WACC",
      "chính sách cổ tức",
      "tỷ lệ chi trả cổ tức",
      "độ bền cổ tức",
      "chính sách mua cổ phiếu quỹ",
      "giá mua lại so với giá trị nội tại",
      "mức pha loãng cổ phiếu",
      "mức sử dụng quyền chọn cổ phiếu",
      "kỷ luật phát hành vốn",
      "kỷ luật M&A",
      "tỷ suất sinh lời sau M&A",
      "mức tăng goodwill",
      "tỷ lệ suy giảm goodwill",
      "chất lượng tích hợp sau M&A",
      "kỷ luật capex",
      "tỷ lệ dự án vượt ngân sách",
      "tỷ lệ dự án chậm tiến độ",
      "độ chính xác hướng dẫn quản trị",
      "tần suất điều chỉnh guidance",
      "mức nhất quán thông điệp quản trị",
      "mức minh bạch KPI",
      "chất lượng hội đồng quản trị",
      "mức độc lập hội đồng quản trị",
      "mức tập trung quyền lực CEO",
      "kế hoạch kế nhiệm lãnh đạo",
      "tỷ lệ sở hữu của quản lý",
      "giao dịch cổ phiếu của nội bộ",
      "thù lao quản lý gắn với giá trị dài hạn",
      "mức độ định giá công bằng giao dịch bên liên quan",
      "mức độ chi phối của cổ đông lớn",
      "bảo vệ cổ đông thiểu số",
      "chất lượng văn hóa kiểm soát",
      "khả năng giữ chân nhân sự chủ chốt",
      "năng lực thực thi chiến lược"
    ]
  },
  {
    "id": "M7",
    "title": "ĐỊNH GIÁ VÀ KỲ VỌNG NGỤ Ý",
    "concepts": [
      "P/E trailing",
      "P/E forward",
      "P/B",
      "EV/EBITDA",
      "EV/EBIT",
      "EV/Sales",
      "FCF yield",
      "dividend yield",
      "PEG",
      "price-to-sales",
      "NAV discount/premium",
      "SOTP",
      "DCF value",
      "residual income value",
      "replacement cost",
      "liquidation value",
      "implied revenue growth",
      "implied margin",
      "implied cost of capital",
      "margin of safety",
      "P/E lịch sử",
      "P/E dự phóng",
      "P/B điều chỉnh tài sản vô hình",
      "P/S",
      "EV/EBITDA điều chỉnh thuê tài sản",
      "EV/EBIT chuẩn hóa chu kỳ",
      "EV/Sales điều chỉnh biên mục tiêu",
      "FCF yield chuẩn hóa vốn lưu động",
      "earnings yield",
      "dividend yield điều chỉnh bền vững",
      "PEG điều chỉnh chất lượng tăng trưởng",
      "giá trên NAV",
      "giá trên giá trị sổ sách hữu hình",
      "giá trên giá trị thay thế",
      "giá trên giá trị thanh lý",
      "giá trị doanh nghiệp trên vốn đầu tư",
      "định giá theo tổng các phần",
      "định giá DCF",
      "định giá thu nhập thặng dư",
      "định giá cổ tức chiết khấu",
      "định giá theo dòng tiền chủ sở hữu",
      "định giá theo dòng tiền doanh nghiệp",
      "tăng trưởng ngụ ý trong giá",
      "biên lợi nhuận ngụ ý trong giá",
      "ROIC ngụ ý trong giá",
      "thời gian tăng trưởng ngụ ý",
      "phần bù rủi ro cổ phiếu ngụ ý",
      "chi phí vốn ngụ ý",
      "xác suất thành công ngụ ý",
      "giá trị quyền chọn tăng trưởng",
      "giá trị tài sản không cốt lõi",
      "chiết khấu tập đoàn",
      "chiết khấu thanh khoản",
      "chiết khấu quản trị",
      "chiết khấu quốc gia",
      "premium kiểm soát",
      "biên an toàn theo phân phối xác suất",
      "độ nhạy định giá với terminal value",
      "độ nhạy định giá với WACC",
      "độ phân tán mục tiêu giá thị trường"
    ]
  },
  {
    "id": "M8",
    "title": "VĨ MÔ, LÃI SUẤT, TỶ GIÁ VÀ LIÊN THỊ TRƯỜNG",
    "concepts": [
      "lãi suất chính sách",
      "lãi suất thực",
      "độ dốc đường cong lợi suất",
      "tăng trưởng tín dụng",
      "cung tiền M2",
      "CPI",
      "PPI",
      "PMI sản xuất",
      "PMI dịch vụ",
      "tăng trưởng GDP",
      "thất nghiệp",
      "tỷ giá doanh thu",
      "tỷ giá chi phí",
      "tỷ giá nợ",
      "dòng vốn ngoại",
      "credit spread",
      "VIX",
      "giá dầu",
      "giá hàng hóa đầu vào",
      "điều kiện tài chính tổng hợp",
      "lãi suất thực kỳ hạn dài",
      "tốc độ tái dốc đường cong lợi suất",
      "độ cong đường cong lợi suất",
      "chênh lệch tín dụng doanh nghiệp",
      "chênh lệch tín dụng chủ quyền",
      "độ thay đổi điều kiện tài chính",
      "tăng trưởng cung tiền",
      "xung lực tín dụng",
      "credit-to-GDP gap",
      "lạm phát tiêu dùng",
      "lạm phát sản xuất",
      "lạm phát kỳ vọng",
      "tăng trưởng GDP thực",
      "GDP danh nghĩa",
      "PMI sản xuất theo đơn hàng xuất khẩu",
      "PMI dịch vụ theo đơn hàng mới",
      "tỷ lệ thất nghiệp",
      "tăng trưởng tiền lương",
      "niềm tin tiêu dùng",
      "niềm tin kinh doanh",
      "cán cân vãng lai",
      "cán cân thương mại",
      "dự trữ ngoại hối",
      "thâm hụt ngân sách",
      "nợ công trên GDP",
      "độ nhạy lợi nhuận với đường cong giá dầu",
      "giá khí tự nhiên",
      "giá điện",
      "giá kim loại công nghiệp",
      "giá nông sản",
      "cước vận tải biển",
      "chỉ số tắc nghẽn chuỗi cung ứng",
      "tỷ giá hiệu lực danh nghĩa",
      "tỷ giá hiệu lực thực",
      "vị thế USD",
      "vị thế EUR",
      "vị thế JPY",
      "vị thế CNY/CNH",
      "thanh khoản USD toàn cầu",
      "rủi ro địa chính trị"
    ]
  },
  {
    "id": "M9",
    "title": "TIN TỨC, TÂM LÝ, CHÚ Ý VÀ MẠNG XÃ HỘI",
    "concepts": [
      "độ tin cậy nguồn tin",
      "mức xác nhận chéo",
      "độ mới của tin",
      "mức bất ngờ",
      "mức liên quan đến dòng tiền",
      "tốc độ lan truyền",
      "tỷ lệ tài khoản độc lập",
      "tỷ lệ nội dung sao chép",
      "mức tập trung vào finfluencer",
      "Google Trends",
      "social volume",
      "sentiment tích cực",
      "sentiment tiêu cực",
      "cường độ ngôn ngữ thúc giục",
      "nguy cơ bot",
      "nguy cơ pump-and-dump",
      "phản ứng giá trước tin",
      "độ bền phản ứng sau tin",
      "mức ảnh hưởng nhà đầu tư trẻ",
      "xung đột lợi ích người đăng",
      "độ tin cậy nguồn tin theo lịch sử hậu kiểm",
      "thời gian đạt xác nhận chéo",
      "tính mới của tin",
      "mức bất ngờ của tin",
      "mức trọng yếu tài chính",
      "khả năng chuyển thành dòng tiền",
      "thời hạn tác động tin",
      "độ mơ hồ ngôn ngữ",
      "mức xung đột lợi ích nguồn",
      "lịch sử chính xác của nguồn",
      "sentiment báo chí",
      "sentiment mạng xã hội",
      "phân cực cảm xúc",
      "cường độ câu chuyện",
      "tốc độ tăng lượt đề cập",
      "số tác giả độc lập",
      "tốc độ lan truyền liên nền tảng",
      "tỷ lệ tương tác bất thường",
      "tỷ lệ tài khoản mới",
      "tỷ lệ bot nghi ngờ",
      "độ phụ thuộc sentiment vào finfluencer chủ chốt",
      "mức độ ảnh hưởng nhà đầu tư trẻ",
      "Google Trends shock",
      "Wikipedia/page-view attention",
      "attention-adjusted turnover",
      "tỷ lệ tin trùng lặp",
      "độ tương đồng ngữ nghĩa giữa các bài đăng",
      "mức sử dụng ngôn ngữ thúc giục",
      "mức cam kết lợi nhuận phi thực tế",
      "rủi ro pump-and-dump",
      "rủi ro short-and-distort",
      "rủi ro deepfake",
      "rủi ro nội dung AI tổng hợp",
      "mức phản ứng giá trước tin",
      "mức phản ứng giá sau tin",
      "độ bền sentiment",
      "sentiment disagreement",
      "mức đảo chiều sau viral",
      "tác động tẩy chay thương hiệu",
      "tác động cộng đồng người dùng"
    ]
  },
  {
    "id": "M10",
    "title": "THỊ TRƯỜNG, KỸ THUẬT VÀ VI CẤU TRÚC",
    "concepts": [
      "xu hướng dài hạn",
      "xu hướng trung hạn",
      "động lượng giá",
      "động lượng lợi nhuận",
      "khối lượng giao dịch",
      "độ rộng thị trường",
      "độ biến động thực tế",
      "độ biến động ngụ ý",
      "bid-ask spread",
      "độ sâu sổ lệnh",
      "price impact",
      "slippage",
      "tỷ lệ giao dịch khối",
      "dòng vốn ETF",
      "dòng vốn ngoại",
      "nợ margin",
      "short interest",
      "futures basis",
      "options skew",
      "chế độ thanh khoản",
      "độ bền xu hướng dài hạn",
      "động lượng 1 tháng",
      "động lượng 3 tháng",
      "động lượng 6 tháng",
      "động lượng 12 tháng",
      "đảo chiều ngắn hạn",
      "đảo chiều dài hạn",
      "độ biến động thực hiện",
      "premium biến động ngụ ý so với thực hiện",
      "volatility skew",
      "volatility term structure",
      "beta thị trường",
      "beta giảm giá",
      "correlation breakdown",
      "maximum drawdown",
      "drawdown duration",
      "volume trung bình",
      "relative volume",
      "volume-price confirmation",
      "on-balance volume",
      "bid-ask spread trong stress",
      "độ sâu sổ lệnh trong điều kiện căng thẳng",
      "độ dốc sổ lệnh",
      "price impact phi tuyến theo quy mô lệnh",
      "Amihud illiquidity",
      "turnover ratio",
      "free-float turnover",
      "block trade activity",
      "foreign flow",
      "institutional flow",
      "retail flow",
      "ETF flow",
      "margin debt",
      "short interest điều chỉnh free float",
      "days to cover",
      "futures basis điều chỉnh chi phí vốn",
      "options put-call ratio",
      "dealer gamma exposure",
      "market breadth",
      "execution slippage"
    ]
  },
  {
    "id": "M11",
    "title": "PHÁP LÝ, KIỂM TOÁN, CÔNG BỐ VÀ RỦI RO LOẠI TRỪ",
    "concepts": [
      "quyền sở hữu tài sản",
      "tính hợp lệ giấy phép",
      "tranh chấp trọng yếu",
      "rủi ro thuế",
      "rủi ro AML/KYC",
      "rủi ro trừng phạt",
      "bảo vệ dữ liệu",
      "an ninh mạng",
      "ý kiến kiểm toán",
      "going concern",
      "restatement",
      "thay đổi kiểm toán viên",
      "vi phạm công bố",
      "giao dịch nội gián",
      "thao túng thị trường",
      "rủi ro hủy niêm yết",
      "rủi ro pha loãng pháp lý",
      "tuân thủ môi trường",
      "tuân thủ lao động",
      "rủi ro hợp đồng trọng yếu",
      "ý kiến kiểm toán ngoại trừ",
      "ý kiến kiểm toán không chấp nhận",
      "ý kiến không thể đưa ra",
      "cảnh báo hoạt động liên tục",
      "lý do và thời điểm thay đổi kiểm toán viên",
      "điều chỉnh hồi tố báo cáo",
      "sai sót trọng yếu",
      "chậm công bố báo cáo",
      "vi phạm nghĩa vụ công bố",
      "chất lượng kiểm soát nội bộ",
      "điểm yếu kiểm soát trọng yếu",
      "rủi ro gian lận doanh thu",
      "rủi ro biển thủ tài sản",
      "rủi ro giao dịch bên liên quan",
      "rủi ro chuyển giá",
      "rủi ro truy thu thuế hồi tố",
      "rủi ro chống độc quyền",
      "rủi ro bảo vệ người tiêu dùng",
      "rủi ro sản phẩm và trách nhiệm pháp lý",
      "rủi ro môi trường",
      "rủi ro giấy phép hoạt động",
      "rủi ro quyền sử dụng đất",
      "rủi ro sở hữu trí tuệ",
      "rủi ro bảo mật dữ liệu",
      "rủi ro an ninh mạng",
      "rủi ro gián đoạn hệ thống",
      "rủi ro nhà cung cấp công nghệ",
      "rủi ro mô hình AI",
      "mức trưởng thành hệ thống AML/KYC",
      "rủi ro trừng phạt quốc tế",
      "rủi ro kiểm soát xuất khẩu",
      "rủi ro hối lộ và tham nhũng",
      "rủi ro lao động",
      "rủi ro an toàn nghề nghiệp",
      "rủi ro kiện tụng tập thể",
      "rủi ro điều tra cơ quan quản lý",
      "rủi ro giao dịch nội gián",
      "rủi ro thao túng thị trường",
      "xác suất hủy niêm yết bắt buộc",
      "rủi ro mất quyền kiểm soát tài sản"
    ]
  },
  {
    "id": "M12",
    "title": "KIỂM ĐỊNH MÔ HÌNH, ĐỘ BỀN THAM SỐ VÀ QUẢN TRỊ DỮ LIỆU",
    "concepts": [
      "chất lượng nguồn dữ liệu",
      "độ đầy đủ dữ liệu",
      "độ trễ dữ liệu",
      "khả năng so sánh",
      "thay đổi chuẩn kế toán",
      "look-ahead bias",
      "survivorship bias",
      "data snooping",
      "overfitting",
      "walk-forward validation",
      "out-of-sample stability",
      "information coefficient",
      "hit rate",
      "monotonicity",
      "factor crowding",
      "concept drift",
      "thay đổi dấu tác động",
      "chi phí giao dịch",
      "độ nhạy tham số",
      "quy tắc hạ trọng số/loại bỏ",
      "độ trễ công bố dữ liệu",
      "tính point-in-time",
      "lịch sử revision dữ liệu",
      "tỷ lệ dữ liệu thiếu",
      "cơ chế bù dữ liệu thiếu",
      "tỷ lệ ngoại lệ",
      "quy tắc xử lý ngoại lệ",
      "độ ổn định định nghĩa",
      "độ nhất quán đơn vị",
      "khả năng tái tạo dữ liệu",
      "lineage dữ liệu",
      "độ tin cậy nguồn dự phòng",
      "mức độ hòa giải nguồn",
      "rủi ro look-ahead bias",
      "rủi ro survivorship bias",
      "rủi ro selection bias",
      "rủi ro data snooping",
      "rủi ro p-hacking",
      "rủi ro overfitting",
      "độ ổn định ngoài mẫu",
      "độ ổn định walk-forward",
      "độ ổn định theo quốc gia",
      "độ ổn định theo ngành",
      "độ ổn định theo regime",
      "IC trung bình",
      "IC decay",
      "hit rate điều chỉnh base rate",
      "độ bền monotonicity ngoài mẫu",
      "turnover của tín hiệu",
      "sai số ước lượng chi phí giao dịch",
      "capacity",
      "crowding",
      "tương quan với biến khác",
      "incremental information value",
      "độ nhạy kết quả với sai số tham số",
      "kết quả ablation",
      "kết quả placebo",
      "kết quả negative control",
      "tốc độ concept drift",
      "quy tắc rollback và kill switch"
    ]
  }
] as Array<{
  id: InvestmentModuleId;
  title: string;
  concepts: string[];
}>;

const VETO_MODULES = new Set<InvestmentModuleId>(["M11"]);
const VALIDATION_MODULES = new Set<InvestmentModuleId>(["M12"]);
const FILTER_MODULES = new Set<InvestmentModuleId>(["M1", "M2"]);

export const INVESTMENT_PARAMETER_CATALOG: InvestmentParameter[] = INVESTMENT_MODULES.flatMap((module) =>
  module.concepts.flatMap((concept, conceptIndex) =>
    PARAMETER_LENSES.map((lens, lensIndex) => ({
      code: `${module.id}-${String(conceptIndex * PARAMETER_LENSES.length + lensIndex + 1).padStart(3, "0")}`,
      moduleId: module.id,
      moduleTitle: module.title,
      concept,
      lens,
      role: VETO_MODULES.has(module.id)
        ? "veto"
        : VALIDATION_MODULES.has(module.id)
          ? "validation"
          : FILTER_MODULES.has(module.id)
            ? "filter"
            : "signal",
    })),
  ),
);

export const INDUSTRY_MODULE_BOOSTS: Record<string, InvestmentModuleId[]> = {
  bank: ["M5", "M8", "M11"],
  banking: ["M5", "M8", "M11"],
  securities: ["M8", "M9", "M10"],
  insurance: ["M5", "M6", "M8", "M11"],
  real_estate: ["M4", "M5", "M11"],
  construction: ["M2", "M4", "M5", "M8"],
  materials: ["M3", "M4", "M8", "M10"],
  energy: ["M3", "M5", "M8", "M11"],
  utilities: ["M5", "M8", "M11"],
  retail: ["M2", "M3", "M4", "M9"],
  consumer: ["M2", "M3", "M6"],
  healthcare: ["M2", "M7", "M11"],
  technology: ["M2", "M3", "M4", "M7", "M9"],
  semiconductor: ["M2", "M3", "M8", "M11"],
  telecom: ["M2", "M3", "M5", "M11"],
  logistics: ["M2", "M3", "M8"],
  transportation: ["M3", "M5", "M8", "M9"],
  agriculture: ["M3", "M4", "M8", "M11"],
  chemicals: ["M3", "M8", "M11"],
  industrial: ["M2", "M3", "M4", "M8"],
  conglomerate: ["M1", "M6", "M7", "M11"],
};

export function getIndustryModuleBoosts(industry?: string) {
  const normalized = (industry ?? "").trim().toLowerCase();
  return INDUSTRY_MODULE_BOOSTS[normalized] ?? [];
}

export function getDynamicParameterWeight(
  parameter: InvestmentParameter,
  options: { industry?: string; dataQuality?: number; lifecycle?: "early" | "growth" | "mature" | "stress" } = {},
) {
  const boosts = getIndustryModuleBoosts(options.industry);
  const relevance = boosts.includes(parameter.moduleId) ? 1.55 : 1;
  const lifecycle = options.lifecycle === "stress" && ["M4", "M5", "M11"].includes(parameter.moduleId)
    ? 1.35
    : options.lifecycle === "growth" && ["M2", "M3", "M6"].includes(parameter.moduleId)
      ? 1.2
      : 1;
  const dataQuality = Math.min(1, Math.max(0.25, (options.dataQuality ?? 75) / 100));
  const roleWeight = parameter.role === "veto" ? 1.4 : parameter.role === "validation" ? 1.2 : 1;
  return Number((relevance * lifecycle * dataQuality * roleWeight).toFixed(2));
}

export function getParameterCatalogStats() {
  return {
    modules: INVESTMENT_MODULES.length,
    concepts: INVESTMENT_MODULES.reduce((total, module) => total + module.concepts.length, 0),
    parameters: INVESTMENT_PARAMETER_CATALOG.length,
  };
}

